name: SeasonsOfConflict
version: '1.0.0'
main: com.seasonsofconflict.SeasonsOfConflict
api-version: '1.20'
description: Hardcore survival with progressive difficulty, seasonal mechanics, and territory control
authors: [mkpvishnu, Claude]
website: https://github.com/mkpvishnu/plugin1

commands:
  team:
    description: Team information and management
    usage: /team [info|list|members]
    aliases: [t]

  quest:
    description: Quest management
    usage: /quest [list|progress]
    aliases: [q]

  territory:
    description: Territory information
    usage: /territory [info|map|capture]
    aliases: [terr]

  revive:
    description: Revive a dead teammate
    usage: /revive <player>

  shop:
    description: Team shop for purchasing items
    usage: /shop [buy <item>]

  stats:
    description: View statistics
    usage: /stats [player]

  leaderboard:
    description: View rankings
    usage: /leaderboard [kills|points|teams]
    aliases: [lb]

  soc:
    description: Admin commands
    usage: /soc <subcommand>
    permission: soc.admin

  compass:
    description: Get a tracking compass
    usage: /compass
    aliases: [track]

permissions:
  soc.admin:
    description: Allows use of admin commands
    default: op
